[phases.setup]
nixPkgs = ["bash", "curl", "wget", "gnupg", "python310"]

commands = [
  "curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
  "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
  "apt-get update",
  "apt-get install -y google-chrome-stable",
  "CHROME_VERSION=$(google-chrome-stable --version | awk '{ print $3 }' | cut -d. -f1)",
  "wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROME_VERSION}.0.0/chromedriver_linux64.zip",
  "unzip /tmp/chromedriver.zip -d /usr/local/bin/",
  "chmod +x /usr/local/bin/chromedriver"
]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:5000 review_dashboard:app"
