[phases.setup]
nixPkgs = ["bash", "curl", "wget", "unzip", "gnupg", "python310"]

commands = [
  "apt-get update",
  # ✅ Install Chromium + matching chromedriver from Ubuntu
  "apt-get install -y chromium-browser chromium-chromedriver",

  # ✅ Debug output
  "chromium-browser --version",
  "chromedriver --version"
]



[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:5000 review_dashboard:app"
