[phases.setup]
nixPkgs = ["bash", "curl", "unzip", "wget", "gnupg", "python310"]

commands = [
  # Google signing key + Chrome repo
  "curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
  "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
  "apt-get update",
  "apt-get install -y google-chrome-stable",

  # ✅ Download known-working LATEST ChromeDriver directly from Google's canonical source
  "CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE) && wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip && unzip /tmp/chromedriver.zip -d /tmp && mv /tmp/chromedriver /usr/local/bin/chromedriver && chmod +x /usr/local/bin/chromedriver"

  # ✅ Debug output (optional)
  "google-chrome-stable --version",
  "chromedriver --version"
]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:5000 review_dashboard:app"
