commands = [
  "curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
  "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
  "apt-get update",
  # 👇 lock to Chrome 125
  "apt-get install -y google-chrome-stable=125.0.6422.141-1 unzip wget",

  # 👇 install matching Chromedriver
  "wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/125.0.6422.141/chromedriver_linux64.zip && unzip /tmp/chromedriver.zip -d /tmp && install -m 755 /tmp/chromedriver /usr/local/bin/chromedriver"
]
