[phases.setup]
nixPkgs = ["bash", "curl", "wget", "gnupg", "python310"]

commands = [
  # Add Google signing key and repo
  "curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
  "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
  "apt-get update",

  # ✅ Install matching Chrome + ChromeDriver from official Google .deb packages
  "apt-get install -y google-chrome-stable google-chrome-stable-driver",

  # ✅ Confirm paths (optional logging)
  "echo '✅ Installed Chrome:' && google-chrome-stable --version",
  "echo '✅ Installed ChromeDriver:' && chromedriver --version"
]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:5000 review_dashboard:app"
